---
abstract: 'A single-threaded multiplexing IMAP server'
author:
  - 'Alex Vandiver <alexmv@mit.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IMAP-Server
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Coro: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  Email::Address: 0
  Email::MIME: 1.862
  Email::MIME::ContentType: 0
  Email::Simple: 1.999
  Encode::IMAPUTF7: 0
  MIME::Base64: 0
  Net::SSLeay: 0
  Net::Server::Coro: 0.3
  Regexp::Common: 0
  Test::More: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.17
