abstract: "A single-threaded multiplexing IMAP server implementation"
author: Alex Vandiver <alexmv@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Net-IMAP-Server
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
version: 0.4
