--- 
abstract: A single-threaded multiplexing IMAP server
author: 
  - Alex Vandiver <alexmv@mit.edu>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-IMAP-Server
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Coro: 0
  Email::Address: 0
  Email::MIME: 0
  Email::MIME::ContentType: 0
  Email::Simple: 1.999
  MIME::Base64: 0
  Net::SSLeay: 0
  Net::Server::Coro: 0.2
  Regexp::Common: 0
  Test::More: 0
version: 0.6
